In [1]:
import numpy as np

# Coding multiple layers of Neural Networks

In [5]:
inputs_to_layer1 = [[1, 2, 3, 2.5],
                    [2., 5., -1., 2],
                    [-1.5, 2.7, 3.3, -0.8]]

layer1_neuron_weights = [[0.2, 0.8, -0.5, 1],
                         [0.5, -0.91, 0.26, -0.5],
                         [-0.26, -0.27, 0.17, 0.87]]

biases_of_layer1_neurons = [2, 3, 0.5]

layer2_neuron_weights = [[0.1, -0.14, 0.5],
                         [-0.5, 0.12, -0.33],
                         [-0.44, 0.73, -0.13]]

biases_of_layer2_neurons = [-1, 2, -0.5]

# Outputs of layer 1 which will get a batch inputs which will be feed as an input to the next layer
layer1_ouputs = np.dot(inputs_to_layer1, np.array(layer1_neuron_weights).T) + biases_of_layer1_neurons

# Final Output of the neural network having 2 layers
layer2_outputs = np.dot(layer1_ouputs, np.array(layer2_neuron_weights).T) + biases_of_layer2_neurons

print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


# Coding a neural netowork of 5 layers where each layer has 1-10 neurons

In [8]:
# Seed for reproducibility
np.random.seed(42)

inputs_to_layer1 = np.array([
    [1.2, -0.7, 3.1, 0.5, 2.3],
    [2.1, 0.9, -1.5, 2.7, -3.2],
    [0.0, -1.2, 1.5, 1.1, 0.9]
])

# Number of features from input
input_size = inputs_to_layer1.shape[1]

# Layer 1 (6 neurons)
layer1_neuron_weights = np.random.randn(6, input_size).tolist()
biases_of_layer1_neurons = np.random.randn(6).tolist()

# Layer 2 (4 neurons)
layer2_neuron_weights = np.random.randn(4, 6).tolist()
biases_of_layer2_neurons = np.random.randn(4).tolist()

# Layer 3 (8 neurons)
layer3_neuron_weights = np.random.randn(8, 4).tolist()
biases_of_layer3_neurons = np.random.randn(8).tolist()

# Layer 4 (5 neurons)
layer4_neuron_weights = np.random.randn(5, 8).tolist()
biases_of_layer4_neurons = np.random.randn(5).tolist()

# Layer 5 (output layer with 3 neurons)
layer5_neuron_weights = np.random.randn(3, 5).tolist()
biases_of_layer5_neurons = np.random.randn(3).tolist()

# Outputs of Layer 1 which will be fed as the input to layer 2
layer1_outputs = np.dot(inputs_to_layer1, np.array(layer1_neuron_weights).T) + biases_of_layer1_neurons

# Outputs of Layer 2 which will be fed as the input to layer 3
layer2_outputs = np.dot(layer1_outputs, np.array(layer2_neuron_weights).T) + biases_of_layer2_neurons

# Outputs of Layer 3 which will be fed as the input to layer 4
layer3_outputs = np.dot(layer2_outputs, np.array(layer3_neuron_weights).T) + biases_of_layer3_neurons

# Outputs of Layer 4 which will be fed as the input to layer 5
layer4_outputs = np.dot(layer3_outputs, np.array(layer4_neuron_weights).T) + biases_of_layer4_neurons

# Outputs of final layer having 3 neurons
final_layer5_outputs = np.dot(layer4_outputs, np.array(layer5_neuron_weights).T) + biases_of_layer5_neurons

print("Output of the final layer having 3 neurons: ", final_layer5_outputs)

print("\nBatch wise outputs -->")
for i in range(len(final_layer5_outputs)):
  print(f"Batch {i+1} output: {final_layer5_outputs[i]}")

Output of the final layer having 3 neurons:  [[101.86183461  72.67893501 -43.42866754]
 [  4.06330904 -12.84601415 -11.1800319 ]
 [ 46.6106128   35.98991001 -20.32862086]]

Batch wise outputs -->
Batch 1 output: [101.86183461  72.67893501 -43.42866754]
Batch 2 output: [  4.06330904 -12.84601415 -11.1800319 ]
Batch 3 output: [ 46.6106128   35.98991001 -20.32862086]
