In [1]:
import numpy as np

# Array Summation using numpy

In [8]:
a = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

print(np.sum(a))
print(np.sum(a, axis=None))

print(np.sum(a, axis=0))
print(np.sum(a, axis=0).shape)

print(np.sum(a, axis=1))
print(np.sum(a, axis=1).shape)

print(np.sum(a, axis=0, keepdims=True))
print(np.sum(a, axis=0, keepdims=True).shape)

print(np.sum(a, axis=1, keepdims=True))
print(np.sum(a, axis=1, keepdims=True).shape)

45
45
[12 15 18]
(3,)
[ 6 15 24]
(3,)
[[12 15 18]]
(1, 3)
[[ 6]
 [15]
 [24]]
(3, 1)


# Broadcasting in numpy

In [14]:
print(np.max(a, axis=0))
print(np.max(a, axis=1))

print(np.max(a, axis=0, keepdims=True))
print(np.max(a, axis=1, keepdims=True))

[7 8 9]
[3 6 9]
[[7 8 9]]
[[3]
 [6]
 [9]]


In [18]:
print(a - np.max(a, axis=1))
print(a - np.max(a, axis=1, keepdims=True))

[[-2 -4 -6]
 [ 1 -1 -3]
 [ 4  2  0]]
[[-2 -1  0]
 [-2 -1  0]
 [-2 -1  0]]
