In [2]:
import numpy as np

# ReLU Activation Function

In [5]:
inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
outputs = np.maximum(0, inputs)
print("Output of ReLU function:", outputs)

Output of ReLU function: [0.  2.  0.  3.3 0.  1.1 2.2 0. ]


# Creating class for ReLU Activation Function

In [6]:
class Activation_ReLU:
  def forward(self, inputs):
    self.output = np.maximum(0, inputs)

activation_relu = Activation_ReLU()
activation_relu.forward(inputs)
print(activation_relu.output)

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


# Softmax Activation Function

In [8]:
inputs = [[1, 2, 3, 2.5],
          [2., 5., -1., 2],
          [-1.5, 2.7, 3.3, -0.8]]

exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=1)

print(probabilities)
print(np.sum(probabilities, axis=1))

[[0.06414769 0.17437149 0.47399085 0.28748998]
 [0.04517666 0.90739747 0.00224921 0.04517666]
 [0.00522984 0.34875873 0.63547983 0.0105316 ]]
[1. 1. 1.]


# Creating class for Softmax Activation Function

In [10]:
class Activation_Softmax:
  def forward(self, inputs):
    exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
    probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
    self.output = probabilities

activation_softmax = Activation_Softmax()
activation_softmax.forward(inputs)
print(activation_softmax.output)

[[0.06414769 0.17437149 0.47399085 0.28748998]
 [0.04517666 0.90739747 0.00224921 0.04517666]
 [0.00522984 0.34875873 0.63547983 0.0105316 ]]
